### ISSUE TITLE
No logs with the recommended setup

### ISSUE THREAD

**Issue by amorozov** [klogging/klogging-spring-boot-starter#6]
I have followed the recommended [setup](#5), including [klogging.json](https://github.com/amorozov/spring-boot-web-validation/blob/main/webflux-kt/src/main/resources/klogging.json), but still can't get any logs:

    [alex@flanky spring-boot-web-validation]$ ./gradlew webflux-kt:bootRun
    
    > Task :webflux-kt:bootRun
    23:19:48.704745054  INFO [                main] :        Configuration : Reading configuration from klogging.json on the classpath
    
      .   ____          _            __ _ _
     /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
    ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
     \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
      '  |____| .__|_| |_|_| |_\__, | / / / /
     =========|_|==============|___/=/_/_/_/
     :: Spring Boot ::                (v3.1.0)

I tried to debug the logging and stepped up to [emitEvent(...) invocation](https://github.com/klogging/klogging/blob/main/src/commonMain/kotlin/io/klogging/Klogger.kt#L72). However IntelliJ Idea informs that the method has not been executed.

I have prepared a [sample project](https://github.com/amorozov/spring-boot-web-validation/). [webflux-kt](https://github.com/amorozov/spring-boot-web-validation/tree/main/webflux-kt) subproject is used to demonstrate the problem

**Comment by mjstrasser** [comment]
Hi @amorozov, thanks for trying Klogging!

You followed my instructions exactly in the README but they were wrong. The `sinks` object in `klogging.json` should be:

```json
  "sinks": {
    "stdout": {
      "renderWith": "RENDER_ANSI",
      "sendTo": "STDOUT"
    }
  },
```

with a `sendTo` key, not a `dispatchTo` key. I changed the key a while ago and forgot to update the docs. I have now updated the README.

Sorry for the inconvenience.

**Comment by amorozov** [comment]
Thank you for the quick response, indeed it solves the issue.
